server:
  port: 8888
  servlet:
#    # 应用的访问路径
    context-path: /m2o
spring:
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        base-url: /m2o
#        type: ASYNC
#        sse-message-endpoint: /m2o/messages
app:
  base-url: https://www.icanshock.fun